sudo: required
cache:
  directories:
  - texlive
before_install:
- |
  if [[ ! -e ./texlive/bin/x86_64-linux/tlmgr ]]; then
    wget http://mirrors.ctan.org/systems/texlive/Source/install-tl-unx.tar.gz -O - | tar -x --gzip
    mv $(ls | grep install) install-tl
    ./install-tl/install-tl -profile texlive.profile
  fi
- export PATH=$(pwd)/texlive/bin/x86_64-linux:$PATH
- sudo apt-get install texlive-full
- sudo apt-get install latexmk
- tlmgr update --self
- tlmgr update --all
- tlmgr install $(cat .tex-dependencies)
script:
- mkdir _build
- cd notesheets
- texfile_list=$(ls *.tex | grep '')
- for filename in $texfile_list
- do
- pdflatex -interaction=nonstopmode -output-directory ../_build $filename
- done
- cd ..
- echo 'do the same thing in practice folder. maybe make a func where we input "notesheets" and it does the above.  then input "practice".'

before_deploy:
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: APIKEYHERE=
  file:
  - _build/algebra.pdf
  - _build/complex-analysis-notes.pdf
  - _build/differential-topology-notes.pdf
  - _build/richards-algebra-book.pdf
  - _build/richards-algebra-book-ii.pdf
  - _build/algebraic-topology.pdf
  - _build/real-analysis-notes.pdf
  - ALL PDF files in _BUILD
  on:
    repo: mareoraft/MATH-1210
    branch: master
