sudo: required
cache:
  directories:
  - texlive
script: # REQUIRED in order for Travis to not error
- echo 'my script'
# Create output pdfs
- mkdir docs/notesheets
- |
  for F1 in $(ls notesheets/*.pdf | grep ''); do
    echo "$F1"
    # F2=$(echo "$F1" | sed s@.tex$@.pdf$@g)
    F2="$F1" # temporary replacement of above line
    F2="docs/$F2"
    echo "$F2"
    mv "$F1" "$F2"
  done
- ls docs/**/*
# Edit webpages to include links for those pdfs
- echo "[click me](notesheets/testoutput.pdf)" >> docs/1220.md
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_KEY # see settings in Travis
  local_dir: docs
  on:
    branch: master
