sudo: required
cache:
  directories:
  - texlive
script: # REQUIRED in order for Travis to not error
- echo 'my script'
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_KEY # see settings in Travis
  on:
    branch: master
