sudo: required
cache:
  directories:
  - texlive
before_install:
- |
  if [[ ! -e ./texlive/bin/x86_64-linux/tlmgr ]]; then
    wget http://mirrors.ctan.org/systems/texlive/Source/install-tl-unx.tar.gz -O - | tar -x --gzip
    mv $(ls | grep install) install-tl
    ./install-tl/install-tl -profile texlive.profile
  fi
- export PATH=$(pwd)/texlive/bin/x86_64-linux:$PATH
- sudo apt-get install texlive-full
- sudo apt-get install latexmk
- tlmgr update --self
- tlmgr update --all
- tlmgr install $(cat .tlmgr-dep)
script: # REQUIRED in order for Travis to not error
- echo 'my script'
# Create output pdfs
- |
  for DI in $(ls -d */ | grep ''); do
    echo "Moving to $DI and compiling all .tex"
    cd "$DI"
    latexmk -pdf -interaction=nonstopmode
    cd ..
    echo "Leaving $DI"
  done
# Move PDFs to correct location
- |
  for DI in $(ls -d */ | grep ''); do
    mkdir docs/$DI
    for F1 in $(ls "$DI"*.pdf | grep ''); do
      echo "Moving $F1 to docs/$DI folder"
      F2="$F1" # temporary replacement of above line
      F2="docs/$F2"
      echo "$F2"
      mv "$F1" "$F2"
    done
  done
- ls docs/**/*
# Edit webpages to include links for those pdfs
- cd docs
- |
  write_section_links() {
    DIR_NAME="$1"
    OUTPUT_FILENAME="$2"
    OUTPUT_SECTION_TITLE="$3"
    OUTPUT_LINK_PREFIX="$4"
    printf "## $OUTPUT_SECTION_TITLE\n" >> "$OUTPUT_FILENAME"
    for FNAME in $(ls "$DIR_NAME" | grep ''); do
        NAME="$OUTPUT_LINK_PREFIX""$FNAME"
        FPATH="$DIR_NAME/$FNAME"
        printf "[$NAME]($FPATH)\n" >> "$OUTPUT_FILENAME"
    done
    printf "\n" >> "$OUTPUT_FILENAME"
  }
- |
  write_file_links() {
    COURSE_NUM="$1"
    FILENAME="$COURSE_NUM.md"
    write_section_links "notesheets-$COURSE_NUM" "$FILENAME" "Notesheets" "notesheet-section-"
    write_section_links "practice-$COURSE_NUM" "$FILENAME" "Supplementary Material" ""
  }
- write_file_links "1210"
- write_file_links "1220"
- cd ..
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_KEY # see settings in Travis
  local_dir: docs
  on:
    branch: master
