sudo: required
cache:
  directories:
  - texlive
script: # REQUIRED in order for Travis to not error
- echo 'my script'
- echo "hi, i'm travis editing your website. gpages now updating from gh-pages" >> docs/1220.md
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_KEY # see settings in Travis
  local_dir: docs
  on:
    branch: master
