sudo: required
cache:
  directories:
  - texlive
before_install:
- |
  if [[ ! -e ./texlive/bin/x86_64-linux/tlmgr ]]; then
    wget http://mirrors.ctan.org/systems/texlive/Source/install-tl-unx.tar.gz -O - | tar -x --gzip
    mv $(ls | grep install) install-tl
    ./install-tl/install-tl -profile texlive.profile
  fi
- export PATH=$(pwd)/texlive/bin/x86_64-linux:$PATH
- sudo apt-get install texlive-full
- sudo apt-get install latexmk
- tlmgr update --self
- tlmgr update --all
- tlmgr install $(cat .tex-deps)
script: # REQUIRED in order for Travis to not error
# Create output pdfs
- |
  for DIR in $(ls -d */ | grep ''); do
    echo "Moving to $DIR and compiling all .tex"
    cd "$DIR"
    for FI in $(ls | grep --regexp="\.tex$"); do
      echo "$FI"
      latexmk -pdf -interaction=nonstopmode "$FI" > output.txt
      EXITCODE="$?"
      if [ $EXITCODE > 0 ]
      then
        cat output.txt
      fi
      echo "$EXITCODE" >> ../exit-codes.txt
      echo "$FI $EXITCODE" >> ../exit-codes-with-filenames.txt
    done
    cd ..
    echo "Left $DIR"
  done
  # Look for non-zero return codes
  RETCODE=0
  for CODE in $(cat exit-codes.txt); do
    RETCODE=$(($RETCODE|$CODE))
  done
  cat exit-codes-with-filenames.txt
  exit $RETCODE
# Move PDFs to correct location
- |
  for DIR in $(ls -d */ | grep ''); do
    mkdir "docs/$DIR"
    for PATH_REL_SRC in $(ls "$DIR"*.pdf | grep ''); do
      PATH_REL_DEST="docs/$PATH_REL_SRC"
      echo "Moving $PATH_REL_SRC to docs/$DIR folder"
      mv "$PATH_REL_SRC" "$PATH_REL_DEST"
    done
  done
- ls docs/**/*
# Edit webpages to include links for those pdfs
- cd docs
- |
  write_section_links() {
    DIR_NAME="$1"
    OUTPUT_FILENAME="$2"
    OUTPUT_SECTION_TITLE="$3"
    OUTPUT_LINK_PREFIX="$4"
    printf "## $OUTPUT_SECTION_TITLE\n" >> "$OUTPUT_FILENAME"
    for FNAME in $(ls "$DIR_NAME" | grep ''); do
        NAME="$OUTPUT_LINK_PREFIX""$FNAME"
        FPATH="$DIR_NAME/$FNAME"
        printf "[$NAME]($FPATH)  \n" >> "$OUTPUT_FILENAME" # Two spaces before \n tells Markdown to generate <br />
    done
    printf "\n" >> "$OUTPUT_FILENAME"
  }
- |
  write_file_links() {
    COURSE_NUM="$1"
    FILENAME="$COURSE_NUM.md"
    write_section_links "notesheets-$COURSE_NUM" "$FILENAME" "Notesheets" "notesheet-section-"
    write_section_links "practice-$COURSE_NUM" "$FILENAME" "Supplementary Material" ""
  }
- write_file_links "1210"
- write_file_links "1220"
- cd ..
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_KEY # see settings in Travis
  local_dir: docs
  on:
    branch: master
