sudo: required
cache:
  directories:
  - texlive
before_install:
# - |
#   if [[ ! -e ./texlive/bin/x86_64-linux/tlmgr ]]; then
#     wget http://mirrors.ctan.org/systems/texlive/Source/install-tl-unx.tar.gz -O - | tar -x --gzip
#     mv $(ls | grep install) install-tl
#     ./install-tl/install-tl -profile texlive.profile
#   fi
# - export PATH=$(pwd)/texlive/bin/x86_64-linux:$PATH
# - sudo apt-get install texlive-full
# - sudo apt-get install latexmk
# - tlmgr update --self
# - tlmgr update --all
# - tlmgr install $(cat .tex-dependencies)
script:
# - mkdir _build
# - cd notesheets
# - texfile_list=$(ls *.tex | grep '')
# - |
#   for filename in $texfile_list; do
#     pdflatex -interaction=nonstopmode -output-directory ../_build $filename
#   done
# - cd ..
# - echo 'do the same thing in practice folder. maybe make a func where we input "notesheets" and it does the above.  then input "practice".'

before_deploy:
- echo 'do things before deploy, such as edit .gitignore'
deploy:
  provider: pages # see https://stackoverflow.com/questions/23277391/how-to-publish-to-github-pages-from-travis-ci#33125422 answer by Yann TM
  skip_cleanup: true
  local_dir: docs/  # or remove this line to upload from root of repo
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  # provider: releases
  # skip_cleanup: true
  # api_key:
  #   secure: vYNWqSsWfr8CWd45K3cHIS8h/ZEwH17h4QNuYnNiokzOeKjlqZncorCqszK3FzIrmpscBljqU3Pp0UmI/fYcmXcz6Iy7tL53apRFEXnz4B6IQ4toWxczkRUlS3GGC6UoirdXQBWnZBH3Bb2ItFE+UG8wjAwSIveSxc5evA5MbCiNXgAEi2VMAc33llldRlcWNnAI6R2uTsoweaUVPw11Bk8xMFf/cbFvgNAg332xt/Rqs5jkAevkrmNPJbhoanpzEtB9CWCYIu9MIQPDhytIIDZI1e/WzhsysatjhnEiHYpP5PwDNX5duzdVl8wnb3RXCmvLh2DysZPULfwvS2uaqHKiBpy9njagdqe19I154j3iwbKTvKd/QS9aIa2R4crRlwTh4ErE6NtXhDhYDqBIejSLIFQYpcZEp+/fAo+a6IDcWKRwElmrcXY1dQpWQkBgJiDctuk1PVd1h3RKre701ZxmTXlX4yak/yXE10khm/Ppd1gXg8jyXg7s4ChrEl2/jM9TVxW5imj6cChhCCo1hUKcHcN5DM2q04LALcN6YDZIev0lRpXjoKFmrdZ6X/SQKG/a+Hn9uoCi4kidJhIyWXo6ajpA0P4apwU0lppU2im1CFwDCLk/mEaWiiCX8iQckIjLYybICZ2QIUF4qy1pJhCMvVlvpg4X05dv1C9yqDk=
  # file:
  # - _build/algebra.pdf
  # - _build/complex-analysis-notes.pdf
  # - _build/differential-topology-notes.pdf
  on:
    # repo: MareoRaft/MATH-1210 # shouldn't be needed because defaults to current repo
    branch: master
